steps:
  # -------------------------------------------------------------------------
  # 1. Construir la imagen Docker
  # Usamos $_REPO_NAME y $PROJECT_ID para hacerlo dinámico
  # -------------------------------------------------------------------------
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', 'europe-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/training-image:latest', 
      '.'
    ]

  # -------------------------------------------------------------------------
  # 2. Subir la imagen a Artifact Registry
  # -------------------------------------------------------------------------
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 
      'europe-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/training-image:latest'
    ]

  # -------------------------------------------------------------------------
  # 3. Lanzar el entrenamiento en Vertex AI
  # Usamos $_REGION y $_BUCKET
  # -------------------------------------------------------------------------
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - ai
      - custom-jobs
      - create
      - --region=${_REGION}
      - --display-name=training-job-$BUILD_ID
      - --worker-pool-spec=machine-type=n1-standard-4,replica-count=1,container-image-uri=europe-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/training-image:latest
      - --base-output-dir=gs://${_BUCKET}/model_output/

  # -------------------------------------------------------------------------
  # 4. Desplegar el modelo automáticamente
  # Pasamos las variables al script de Python
  # -------------------------------------------------------------------------
  - name: 'python:3.9-slim'
    entrypoint: /bin/sh
    args:
      - -c
      - |
        pip install google-cloud-aiplatform
        python deploy.py \
          --project_id=$PROJECT_ID \
          --region=${_REGION} \
          --bucket=${_BUCKET} \
          --name=mi-modelo-regresion

# Imágenes resultantes
images:
  - 'europe-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/training-image:latest'

# ⚠️ ESTA SECCIÓN ES OPCIONAL PERO RECOMENDADA
# Define valores por defecto por si se te olvida pasarlos desde GitHub
substitutions:
    _REGION: europe-west4
    _BUCKET: dataflow_vertex
    _REPO_NAME: images